export enum EVENTS {
	EVENTS_LOAD_START = 'EVENT_LOAD_START',
	EVENTS_LOAD_DONE = 'EVENT_LOAD_DONE',
	EVENTS_LOAD_FAIL = 'EVENT_LOAD_FAIL'
}

export enum RESERVATIONS {
	RESERVATIONS_LOAD_START = 'RESERVATIONS_LOAD_START',
	RESERVATIONS_LOAD_DONE = 'RESERVATIONS_LOAD_DONE',
	RESERVATIONS_LOAD_FAIL = 'RESERVATIONS_LOAD_FAIL',
	RESERVATIONS_CLEAR = 'RESERVATIONS_CLEAR'
}

export enum SHIFTS_TIME_OFF {
	SHIFTS_TIME_OFF_LOAD_START = 'SHIFTS_TIME_OFF_LOAD_START',
	SHIFTS_TIME_OFF_LOAD_DONE = 'SHIFTS_TIME_OFF_LOAD_DONE',
	SHIFTS_TIME_OFF_LOAD_FAIL = 'SHIFTS_TIME_OFF_LOAD_FAIL',
	SHIFTS_TIME_OFF_CLEAR = 'SHIFTS_TIME_OFF_CLEAR'
}

export enum EVENT_DETAIL {
	EVENT_DETAIL_LOAD_START = 'EVENT_DETAIL_LOAD_START',
	EVENT_DETAIL_LOAD_DONE = 'EVENT_DETAIL_LOAD_DONE',
	EVENT_DETAIL_LOAD_FAIL = 'EVENT_DETAIL_LOAD_FAIL'
}
