/* eslint-disable import/prefer-default-export */
const fakeMontlyEvents = {
	employees: [
		{
			id: 'd55d56a7-de69-4710-a7e0-b5ee76fb5fa0',
			firstName: 'Peter',
			lastName: 'Sveter',
			email: 'test+pesve@goodrequest.com',
			color: '#0E9384',
			image: {
				id: '5af0c91e-c9b5-45ef-bf4c-abea941a1c48',
				original: 'https://d1pfrdq2i86yn4.cloudfront.net/employees/229d53ba-9bed-4060-a2f1-50d2992634d4.png',
				resizedImages: {
					thumbnail: 'https://d1pfrdq2i86yn4.cloudfront.net/employees/229d53ba-9bed-4060-a2f1-50d2992634d4-thumbnail.png',
					small: 'https://d1pfrdq2i86yn4.cloudfront.net/employees/229d53ba-9bed-4060-a2f1-50d2992634d4-small.png',
					medium: 'https://d1pfrdq2i86yn4.cloudfront.net/employees/229d53ba-9bed-4060-a2f1-50d2992634d4-medium.png',
					large: 'https://d1pfrdq2i86yn4.cloudfront.net/employees/229d53ba-9bed-4060-a2f1-50d2992634d4-large.png'
				},
				fileName: '229d53ba-9bed-4060-a2f1-50d2992634d4.png',
				isAutogenerated: true
			}
		},
		{
			id: '0fe51bab-5a01-41bb-9a11-37072c8c6165',
			firstName: 'Jolana',
			lastName: 'Horepredková',
			email: 'test+j.horepredkova@goodrequest.com',
			color: '#088AB2',
			image: {
				id: '6692227f-9c51-4e8d-8526-4100c0f00bca',
				original: 'https://d1pfrdq2i86yn4.cloudfront.net/employees/f66562ba-944d-4cbf-9794-262a2e66fa93_dahiana-waszaj-Xbe20Z_DlDs-unsplash.jpg',
				resizedImages: {
					thumbnail: 'https://d1pfrdq2i86yn4.cloudfront.net/employees/f66562ba-944d-4cbf-9794-262a2e66fa93_dahiana-waszaj-Xbe20Z_DlDs-unsplash-thumbnail.jpg',
					small: 'https://d1pfrdq2i86yn4.cloudfront.net/employees/f66562ba-944d-4cbf-9794-262a2e66fa93_dahiana-waszaj-Xbe20Z_DlDs-unsplash-small.jpg',
					medium: 'https://d1pfrdq2i86yn4.cloudfront.net/employees/f66562ba-944d-4cbf-9794-262a2e66fa93_dahiana-waszaj-Xbe20Z_DlDs-unsplash-medium.jpg',
					large: 'https://d1pfrdq2i86yn4.cloudfront.net/employees/f66562ba-944d-4cbf-9794-262a2e66fa93_dahiana-waszaj-Xbe20Z_DlDs-unsplash-large.jpg'
				},
				fileName: 'dahiana-waszaj-Xbe20Z_DlDs-unsplash.jpg',
				isAutogenerated: false
			}
		},
		{
			id: 'b699c13e-4f46-4166-a5b4-82e606eb6291',
			firstName: 'Partner',
			lastName: 'User',
			email: 'test.confirmed_partneruser@goodrequest.com',
			color: '#3E4784',
			image: {
				id: '8cd4cc37-48eb-4b65-8f74-c0184faf00ff',
				original: 'https://d1pfrdq2i86yn4.cloudfront.net/employees/603b0c9d-22aa-4c6f-89e2-b714198d2943_NdtrLNijKPdzHIHjcFiOYiMHrDmrEJ3eqbdJZWaeofE-2048x1536.jpg',
				resizedImages: {
					thumbnail:
						'https://d1pfrdq2i86yn4.cloudfront.net/employees/603b0c9d-22aa-4c6f-89e2-b714198d2943_NdtrLNijKPdzHIHjcFiOYiMHrDmrEJ3eqbdJZWaeofE-2048x1536-thumbnail.jpg',
					small: 'https://d1pfrdq2i86yn4.cloudfront.net/employees/603b0c9d-22aa-4c6f-89e2-b714198d2943_NdtrLNijKPdzHIHjcFiOYiMHrDmrEJ3eqbdJZWaeofE-2048x1536-small.jpg',
					medium: 'https://d1pfrdq2i86yn4.cloudfront.net/employees/603b0c9d-22aa-4c6f-89e2-b714198d2943_NdtrLNijKPdzHIHjcFiOYiMHrDmrEJ3eqbdJZWaeofE-2048x1536-medium.jpg',
					large: 'https://d1pfrdq2i86yn4.cloudfront.net/employees/603b0c9d-22aa-4c6f-89e2-b714198d2943_NdtrLNijKPdzHIHjcFiOYiMHrDmrEJ3eqbdJZWaeofE-2048x1536-large.jpg'
				},
				fileName: 'NdtrLNijKPdzHIHjcFiOYiMHrDmrEJ3eqbdJZWaeofE-2048x1536.jpg',
				isAutogenerated: false
			}
		},
		{
			id: '27604557-0508-4f54-babf-9e8ce281d4a7',
			email: 'lukas.siarny@gmail.com',
			color: '#4CA30D',
			image: {
				id: '00000000-0000-0000-0000-000000000027',
				original: 'https://d1pfrdq2i86yn4.cloudfront.net/employees/default_avatar.png',
				resizedImages: {
					thumbnail: 'https://d1pfrdq2i86yn4.cloudfront.net/employees/default_avatar-thumbnail.png',
					small: 'https://d1pfrdq2i86yn4.cloudfront.net/employees/default_avatar-small.png',
					medium: 'https://d1pfrdq2i86yn4.cloudfront.net/employees/default_avatar-medium.png',
					large: 'https://d1pfrdq2i86yn4.cloudfront.net/employees/default_avatar-large.png'
				},
				fileName: 'default_avatar.png',
				isAutogenerated: true
			}
		},
		{
			id: '8b85a04d-bf48-4bea-9bee-71c81d506c0f',
			email: 'lukas.siarny@goodrequest.com',
			color: '#4F7A21',
			image: {
				id: '00000000-0000-0000-0000-000000000027',
				original: 'https://d1pfrdq2i86yn4.cloudfront.net/employees/default_avatar.png',
				resizedImages: {
					thumbnail: 'https://d1pfrdq2i86yn4.cloudfront.net/employees/default_avatar-thumbnail.png',
					small: 'https://d1pfrdq2i86yn4.cloudfront.net/employees/default_avatar-small.png',
					medium: 'https://d1pfrdq2i86yn4.cloudfront.net/employees/default_avatar-medium.png',
					large: 'https://d1pfrdq2i86yn4.cloudfront.net/employees/default_avatar-large.png'
				},
				fileName: 'default_avatar.png',
				isAutogenerated: true
			}
		},
		{
			id: '8e2fb39a-2ac0-4a9f-b97b-c714a2f8ec13',
			firstName: 'Adam',
			lastName: 'Mitrek',
			email: 'test+a.mitrek@goodrequest.com',
			color: '#099250',
			image: {
				id: '9d852714-9bab-44a0-a366-c7749a353a01',
				original: 'https://d1pfrdq2i86yn4.cloudfront.net/employees/de6c5965-c266-4138-b0e0-e518a6ff8719_avatar1.png',
				resizedImages: {
					thumbnail: 'https://d1pfrdq2i86yn4.cloudfront.net/employees/de6c5965-c266-4138-b0e0-e518a6ff8719_avatar1-thumbnail.png',
					small: 'https://d1pfrdq2i86yn4.cloudfront.net/employees/de6c5965-c266-4138-b0e0-e518a6ff8719_avatar1-small.png',
					medium: 'https://d1pfrdq2i86yn4.cloudfront.net/employees/de6c5965-c266-4138-b0e0-e518a6ff8719_avatar1-medium.png',
					large: 'https://d1pfrdq2i86yn4.cloudfront.net/employees/de6c5965-c266-4138-b0e0-e518a6ff8719_avatar1-large.png'
				},
				fileName: 'avatar1.png',
				isAutogenerated: false
			}
		}
	],
	calendarEvents: {
		'2023-02-01': [
			{
				id: 'id1',
				employeeId: 'd55d56a7-de69-4710-a7e0-b5ee76fb5fa0',
				eventsCount: 9,
				eventsDuration: 500
			},
			{
				id: 'id2',
				employeeId: '0fe51bab-5a01-41bb-9a11-37072c8c6165',
				eventsCount: 7,
				eventsDuration: 400
			},
			{
				id: 'id3',
				employeeId: 'b699c13e-4f46-4166-a5b4-82e606eb6291',
				eventsCount: 5,
				eventsDuration: 270
			},
			{
				id: 'id4',
				employeeId: '27604557-0508-4f54-babf-9e8ce281d4a7',
				eventsCount: 7,
				eventsDuration: 450
			},
			{
				id: 'id5',
				employeeId: '8b85a04d-bf48-4bea-9bee-71c81d506c0f',
				eventsCount: 3,
				eventsDuration: 500
			},
			{
				id: 'id6',
				employeeId: '8e2fb39a-2ac0-4a9f-b97b-c714a2f8ec13',
				eventsCount: 3,
				eventsDuration: 350
			}
		],
		'2023-02-02': [
			{
				id: 'id7',
				employeeId: 'd55d56a7-de69-4710-a7e0-b5ee76fb5fa0',
				eventsCount: 9,
				eventsDuration: 500
			},
			{
				id: 'id9',
				employeeId: 'b699c13e-4f46-4166-a5b4-82e606eb6291',
				eventsCount: 3,
				eventsDuration: 700
			},
			{
				id: 'id10',
				employeeId: '27604557-0508-4f54-babf-9e8ce281d4a7',
				eventsCount: 1,
				eventsDuration: 415
			}
		],
		'2023-02-03': [
			{
				id: 'id11',
				employeeId: 'd55d56a7-de69-4710-a7e0-b5ee76fb5fa0',
				eventsCount: 9,
				eventsDuration: 500
			},
			{
				id: 'id12',
				employeeId: '0fe51bab-5a01-41bb-9a11-37072c8c6165',
				eventsCount: 7,
				eventsDuration: 400
			},
			{
				id: 'id13',
				employeeId: 'b699c13e-4f46-4166-a5b4-82e606eb6291',
				eventsCount: 5,
				eventsDuration: 270
			},
			{
				id: 'id14',
				employeeId: '27604557-0508-4f54-babf-9e8ce281d4a7',
				eventsCount: 7,
				eventsDuration: 450
			},
			{
				id: 'id15',
				employeeId: '8b85a04d-bf48-4bea-9bee-71c81d506c0f',
				eventsCount: 3,
				eventsDuration: 500
			},
			{
				id: 'id16',
				employeeId: '8e2fb39a-2ac0-4a9f-b97b-c714a2f8ec13',
				eventsCount: 3,
				eventsDuration: 350
			}
		]
	}
}

export default { data: fakeMontlyEvents }
