// eslint-disable-next-line import/prefer-default-export
export enum CATEGORY_PARAMETERS {
	CATEGORY_PARAMETERS_LOAD_START = 'CATEGORY_PARAMETERS_LOAD_START',
	CATEGORY_PARAMETERS_LOAD_DONE = 'CATEGORY_PARAMETERS_LOAD_DONE',
	CATEGORY_PARAMETERS_LOAD_FAIL = 'CATEGORY_PARAMETERS_LOAD_FAIL'
}
