// eslint-disable-next-line import/prefer-default-export
export enum DOCUMENTS {
	DOCUMENTS_LOAD_START = 'DOCUMENTS_LOAD_START',
	DOCUMENTS_LOAD_DONE = 'DOCUMENTS_LOAD_DONE',
	DOCUMENTS_LOAD_FAIL = 'DOCUMENTS_LOAD_FAIL'
}

export enum DOCUMENT {
	DOCUMENT_LOAD_START = 'DOCUMENT_LOAD_START',
	DOCUMENT_LOAD_DONE = 'DOCUMENT_LOAD_DONE',
	DOCUMENT_LOAD_FAIL = 'DOCUMENT_LOAD_FAIL'
}
