export enum USERS {
	USERS_LOAD_START = 'USERS_LOAD_START',
	USERS_LOAD_DONE = 'USERS_LOAD_DONE',
	USERS_LOAD_FAIL = 'USERS_LOAD_FAIL'
}

export enum AUTH_USER {
	AUTH_USER_LOAD_START = 'AUTH_USER_LOAD_START',
	AUTH_USER_LOAD_DONE = 'AUTH_USER_LOAD_DONE',
	AUTH_USER_LOAD_FAIL = 'AUTH_USER_LOAD_FAIL'
}

export enum AUTH_USER_SETTINGS {
	AUTH_USER_SETTINGS_LOAD_START = 'AUTH_USER_SETTINGS_LOAD_START',
	AUTH_USER_SETTINGS_LOAD_DONE = 'AUTH_USER_SETTINGS_LOAD_DONE',
	AUTH_USER_SETTINGS_LOAD_FAIL = 'AUTH_USER_SETTINGS_LOAD_FAIL',
	UPDATE_AUTH_USER_SETTINGS = 'UPDATE_AUTH_USER_SETTINGS'
}

export enum USER {
	USER_LOAD_START = 'USER_LOAD_START',
	USER_LOAD_DONE = 'USER_LOAD_DONE',
	USER_LOAD_FAIL = 'USER_LOAD_FAIL'
}
