// eslint-disable-next-line import/prefer-default-export
export enum AUTH_USER {
	AUTH_USER_LOAD_START = 'AUTH_USER_LOAD_START',
	AUTH_USER_LOAD_DONE = 'AUTH_USER_LOAD_DONE',
	AUTH_USER_LOAD_FAIL = 'AUTH_USER_LOAD_FAIL'
}

export enum USER {
	USER_LOAD_START = 'USER_LOAD_START',
	USER_LOAD_DONE = 'USER_LOAD_DONE',
	USER_LOAD_FAIL = 'USER_LOAD_FAIL'
}

export enum USERS {
	USERS_LOAD_START = 'USERS_LOAD_START',
	USERS_LOAD_DONE = 'USERS_LOAD_DONE',
	USERS_LOAD_FAIL = 'USERS_LOAD_FAIL'
}

export enum NOTINO_USERS {
	NOTINO_USERS_LOAD_START = 'NOTINO_USERS_LOAD_START',
	NOTINO_USERS_LOAD_DONE = 'NOTINO_USERS_LOAD_DONE',
	NOTINO_USERS_LOAD_FAIL = 'NOTINO_USERS_LOAD_FAIL'
}

export enum PENDING_INVITES {
	PENDING_INVITES_LOAD_START = 'PENDING_INVITES_LOAD_START',
	PENDING_INVITES_LOAD_DONE = 'PENDING_INVITES_LOAD_DONE',
	PENDING_INVITES_LOAD_FAIL = 'PENDING_INVITES_LOAD_FAIL'
}
