image: node:16.14.0
pipelines:
  branches:
    development:
      - step:
          name: Install npm modules
          script:
            - npm install --legacy-peer-deps
          caches:
            - node
          artifacts:
            - node_modules/**
      - parallel:
          - step:
              name: Lint checking
              script:
                - npm run lint
          - step:
              name: Build and push docker image
              script:
                # push source maps to sentry service
                - HOST=testServer SENTRY_AUTH_TOKEN=$SENTRY_AUTH_TOKEN SENTRY_URL=$SENTRY_URL CI=false npm run release
                # remove source maps from bundle build
                - find build/static/js/ -name "*.map" -type f -delete
                - docker build -t registry.goodrequest.com/notino-b2b-web:development -f docker/development/Dockerfile.web .
                - docker login --username $DOCKER_REGISTRY_USERNAME --password $DOCKER_REGISTRY_PASSWORD registry.goodrequest.com
                - docker push registry.goodrequest.com/notino-b2b-web:development
    test:
      - step:
          name: Install npm modules
          script:
            - npm install --legacy-peer-deps
          caches:
            - node
          artifacts:
            - node_modules/**
      - parallel:
          - step:
              name: Lint checking
              script:
                - npm run lint
          - step:
              name: Build and push docker image
              script:
                # push source maps to sentry service
                - HOST=testServer SENTRY_AUTH_TOKEN=$SENTRY_AUTH_TOKEN SENTRY_URL=$SENTRY_URL CI=false npm run release
                # remove source maps from bundle build
                - find build/static/js/ -name "*.map" -type f -delete
                - docker build -t registry.goodrequest.com/notino-b2b-web:test -f docker/test/Dockerfile.web .
                - docker login --username $DOCKER_REGISTRY_USERNAME --password $DOCKER_REGISTRY_PASSWORD registry.goodrequest.com
                - docker push registry.goodrequest.com/notino-b2b-web:test
    uat:
      - step:
          name: Install npm modules
          script:
            - npm install --legacy-peer-deps
          caches:
            - node
          artifacts:
            - node_modules/**
      - step:
          name: Build and push docker image
          script:
            # push source maps to sentry service
            - HOST=testServer SENTRY_AUTH_TOKEN=$SENTRY_AUTH_TOKEN SENTRY_URL=$SENTRY_URL CI=false npm run release
            # remove source maps from bundle build
            - find build/static/js/ -name "*.map" -type f -delete
            - docker build -t 809210427750.dkr.ecr.eu-central-1.amazonaws.com/notino-b2b-web:uat -f docker/uat/Dockerfile.web .
            - docker login --username $AWS_CONTAINER_REGISTRY_USER --password $AWS_CONTAINER_REGISTRY_PASSWORD 809210427750.dkr.ecr.eu-central-1.amazonaws.com
            - docker push 809210427750.dkr.ecr.eu-central-1.amazonaws.com/notino-b2b-web:uat
  pull-requests:
    'NOT-*':
      - step:
          name: Install npm modules
          script:
            - npm install --legacy-peer-deps
          caches:
            - node
          artifacts:
            - node_modules/**
      - parallel:
          - step:
              name: Lint checking
              script:
                - npm run lint
          - step:
              name: Build and push docker image
              script:
                - CI=false npm run build
options:
  docker: true
  max-time: 20
  size: 2x
