image: node:16.14.0
pipelines:
  branches:
    development:
      - step:
          name: Install npm modules
          script:
            - npm install --legacy-peer-deps
          caches:
            - node
      - parallel:
          - step:
              name: Lint checking
              caches:
                - node
              script:
                - npm run lint
          - step:
              name: Build and push docker image
              caches:
                - node
              script:
                - CI=false npm run build
                - docker build -t registry.goodrequest.com/notino-b2b-web:development -f docker/development/Dockerfile.web .
                - docker login --username $DOCKER_REGISTRY_USERNAME --password $DOCKER_REGISTRY_PASSWORD registry.goodrequest.com
                - docker push registry.goodrequest.com/notino-b2b-web:development
    test:
      - step:
          name: Install npm modules
          script:
            - npm install --legacy-peer-deps
          caches:
            - node
      - parallel:
          - step:
              name: Lint checking
              caches:
                - node
              script:
                - npm run lint
          - step:
              name: Build and push docker image
              caches:
                - node
              script:
                - SENTRY_AUTH_TOKEN=$SENTRY_AUTH_TOKEN SENTRY_URL=$SENTRY_URL CI=false npm run release
                - docker build -t registry.goodrequest.com/notino-b2b-web:test -f docker/test/Dockerfile.web .
                - docker login --username $DOCKER_REGISTRY_USERNAME --password $DOCKER_REGISTRY_PASSWORD registry.goodrequest.com
                - docker push registry.goodrequest.com/notino-b2b-web:test
  pull-requests:
    'NOTINO-*':
      - step:
          name: Install npm modules
          script:
            - npm install --legacy-peer-deps
          caches:
            - node
      - parallel:
          - step:
              name: Lint checking
              caches:
                - node
              script:
                - npm run lint
          - step:
              name: Build and push docker image
              caches:
                - node
              script:
                - CI=false npm run build
options:
  docker: true
  max-time: 20
  size: 2x
