version: '3.8'

services:
  database_test:
    build:
      context: ./notino_backend/.
      dockerfile: ./docker/local/postgres/Dockerfile
    ports:
      - "25432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=notino_test
  redis:
    image: redis
    ports:
      - "16379:6379"
    command: redis-server --requirepass PLEASE_CHANGE_ME
  localstack:
    image: localstack/localstack:0.14.3
    network_mode: bridge
    ports:
      - "127.0.0.1:4510-4559:4510-4559"  # external service port range
      - "127.0.0.1:4566:4566"            # LocalStack Edge Proxy
    environment:
      - DEFAULT_REGION=eu-central-1
      - SERVICES=s3
    volumes:
    # after init container create bucket
      - './notino_backend/docker/CI/localstack:/docker-entrypoint-initaws.d'
  backend:
    build:
        context: ./notino_backend/.
        dockerfile: ./docker/CI/Dockerfile.api
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=redis://:PLEASE_CHANGE_ME@redis:6379
      - POSTGRESQL_URL=postgresql://postgres:root@database_test:5432/notino_test
      - JWT_SECRET=ewfjweiofjowimfkewnmfoin
      - AWS_S3_BUCKET=sample-bucket
      - AWS_S3_REGION=eu-central-1
      - AWS_S3_ACCESS_KEY_ID=test
      - AWS_S3_SECRET_KEY=test
      - AWS_KEYPAIR_ID=test
      - PORT=3000
      - NODE_ENV=development
      - AWS_S3_PUBLIC_URL=http://sample-bucket.s3.eu-cental-1.localstack:4566
      - AWS_S3_ENDPOINT=http://s3.eu-cental-1.localstack:4566
      - SERVICES_SUGGESTION_EMAILS=test@goodrequest.com
      # in bitbucket pipeline do not work docker.host.internal instead of it has to be used $BITBUCKET_DOCKER_HOST_INTERNAL variable
      - SMTP_HOST=$BITBUCKET_DOCKER_HOST_INTERNAL
      # mail server is running with cypress test define in cypress plugins
      - SMTP_PORT=7777
      - SMTP_FROM_ADDRESS=e2e@goodrequest.com
    depends_on:
      - "localstack"
      - "redis"
      - "database_test"
    volumes:
      - './notino_backend/logs:/home/app/logs'
  frontend:
    build:
        context: .
        dockerfile: ./docker/CI/Dockerfile
    ports:
      - "80:80"
    volumes:
      - './docker/CI/nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - "backend"
