version: '3.8'

services:
  database_test:
    build:
      context: ./notino_backend/.
      dockerfile: ./docker/CI/postgres/Dockerfile
    ports:
      - "25432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=notino_test
  init_worker:
    build:
      context: ./notino_backend/.
      dockerfile: ./docker/CI/initWorker/Dockerfile
    environment:
      - NODE_ENV=production
      - POSTGRESQL_URL=postgresql://postgres:root@database_test:5432/notino_test
      - AWS_S3_BUCKET=sample-bucket
      - AWS_S3_REGION=eu-central-1
      - AWS_S3_ACCESS_KEY_ID=test
      - AWS_S3_SECRET_KEY=test
      - AWS_KEYPAIR_ID=test
      - AWS_S3_PUBLIC_URL=http://sample-bucket.s3.eu-central-1.localhost:4566
      - AWS_S3_ENDPOINT=http://s3.eu-central-1.localhost:4566
    # NOTE: localy can be test with export BITBUCKET_DOCKER_HOST_INTERNAL=host.docker.internal (as a IP address 192.168.65.2 check by ping host.docker.internal from container)
    extra_hosts:
      - "sample-bucket.s3.eu-central-1.localhost:$BITBUCKET_DOCKER_HOST_INTERNAL"
      - "s3.eu-central-1.localhost:$BITBUCKET_DOCKER_HOST_INTERNAL"
    depends_on:
      - "database_test"
  redis:
    image: redis
    ports:
      - "16379:6379"
    command: redis-server --requirepass PLEASE_CHANGE_ME
  localstack:
    image: localstack/localstack:0.14.3
    ports:
      - "4510-4559:4510-4559" # external service port range
      - "4566:4566" # LocalStack Edge Proxy
    environment:
      - DEFAULT_REGION=eu-central-1
      - SERVICES=s3
    volumes:
      # after init container create bucket
      - './notino_backend/docker/CI/localstack:/docker-entrypoint-initaws.d'
  backend_0:
    build:
      context: ./notino_backend/.
      dockerfile: ./docker/CI/api/Dockerfile
      args:
        PORT: 3000
    ports:
      - "3000:3000"
    # NOTE: localy can be test with export BITBUCKET_DOCKER_HOST_INTERNAL=host.docker.internal (as a IP address 192.168.65.2 check by ping host.docker.internal from container)
    extra_hosts:
      - "sample-bucket.s3.eu-central-1.localhost:$BITBUCKET_DOCKER_HOST_INTERNAL"
      - "s3.eu-central-1.localhost:$BITBUCKET_DOCKER_HOST_INTERNAL"
    environment:
      - REDIS_URL=redis://:PLEASE_CHANGE_ME@redis:6379
      - POSTGRESQL_URL=postgresql://postgres:root@database_test:5432/notino_test
      - JWT_SECRET=ewfjweiofjowimfkewnmfoin
      - AWS_S3_BUCKET=sample-bucket
      - AWS_S3_REGION=eu-central-1
      - AWS_S3_ACCESS_KEY_ID=test
      - AWS_S3_SECRET_KEY=test
      - AWS_KEYPAIR_ID=test
      - PORT=3000
      - NODE_ENV=production
      - AWS_S3_PUBLIC_URL=http://sample-bucket.s3.eu-central-1.localhost:4566
      - AWS_S3_ENDPOINT=http://s3.eu-central-1.localhost:4566
      - SERVICES_SUGGESTION_EMAILS=test@goodrequest.com
      - USE_CLOUD_WATCH=false
      # in bitbucket pipeline do not work docker.host.internal instead of it has to be used $BITBUCKET_DOCKER_HOST_INTERNAL variable
      - SMTP_HOST=$BITBUCKET_DOCKER_HOST_INTERNAL
      # mail server is running with cypress test define in cypress plugins
      - SMTP_PORT=7777
      - BASIC_MAINTENANCE_USERNAME=admin
      - BASIC_MAINTENANCE_PASSWORD=Lopaty123.
    depends_on:
      - "redis"
      - "database_test"
      - "init_worker"
    volumes:
      - './notino_backend/logs/0:/home/app/logs'
      # mount folder with e2e seeders for development purposes (editing and executing seeders in running container)
      - './notino_backend/src/db/seeders/e2e:/home/app/src/db/seeders/e2e'
  backend_1:
    build:
      context: ./notino_backend/.
      dockerfile: ./docker/CI/api/Dockerfile
      args:
        PORT: 3001
    ports:
      - "3001:3000"
    # NOTE: localy can be test with export BITBUCKET_DOCKER_HOST_INTERNAL=host.docker.internal (as a IP address 192.168.65.2 check by ping host.docker.internal from container)
    extra_hosts:
      - "sample-bucket.s3.eu-central-1.localhost:$BITBUCKET_DOCKER_HOST_INTERNAL"
      - "s3.eu-central-1.localhost:$BITBUCKET_DOCKER_HOST_INTERNAL"
    environment:
      - REDIS_URL=redis://:PLEASE_CHANGE_ME@redis:6379
      - POSTGRESQL_URL=postgresql://postgres:root@database_test:5432/notino_test_1
      - JWT_SECRET=ewfjweiofjowimfkewnmfoin
      - AWS_S3_BUCKET=sample-bucket
      - AWS_S3_REGION=eu-central-1
      - AWS_S3_ACCESS_KEY_ID=test
      - AWS_S3_SECRET_KEY=test
      - AWS_KEYPAIR_ID=test
      - PORT=3000
      - NODE_ENV=production
      - AWS_S3_PUBLIC_URL=http://sample-bucket.s3.eu-central-1.localhost:4566
      - AWS_S3_ENDPOINT=http://s3.eu-central-1.localhost:4566
      - SERVICES_SUGGESTION_EMAILS=test@goodrequest.com
      - USE_CLOUD_WATCH=false
      # in bitbucket pipeline do not work docker.host.internal instead of it has to be used $BITBUCKET_DOCKER_HOST_INTERNAL variable
      - SMTP_HOST=$BITBUCKET_DOCKER_HOST_INTERNAL
      # mail server is running with cypress test define in cypress plugins
      - SMTP_PORT=7777
      - BASIC_MAINTENANCE_USERNAME=admin
      - BASIC_MAINTENANCE_PASSWORD=Lopaty123.
    depends_on:
      - "redis"
      - "database_test"
      - "init_worker"
    volumes:
      - './notino_backend/logs/1:/home/app/logs'
      # mount folder with e2e seeders for development purposes (editing and executing seeders in running container)
      - './notino_backend/src/db/seeders/e2e:/home/app/src/db/seeders/e2e'
  frontend:
    environment:
      - REACT_APP_GOOGLE_MAPS_API_KEY=testGoogleAPIKey
      - FULLCALENDAR_LICENSE_KEY=testKey
      - REACT_APP_SENTRY_ENV=e2e
      - REACT_APP_SENTRY_DSN=https://123@sentry.dev/1
      - REACT_APP_GOOGLE_OAUTH_CLIENT_ID=841411372013-83m99dm3baeqpc5lcokfv153jbp52kbr.apps.googleusercontent.com
      - REACT_APP_MS_OAUTH_CLIENT_ID=5a15a7fb-6773-43a9-aaec-b8ecd91862fa
    build:
      context: .
      dockerfile: ./docker/CI/Dockerfile
    ports:
      - "80:80"
      - "81:81"
    volumes:
      - './docker/CI/nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - "backend_0"
      - "backend_1"
  scheduler:
    build:
      context: ./notino_backend/.
      dockerfile: ./docker/CI/scheduler/Dockerfile
    ports:
      - "7000:7000"
      # NOTE: localy can be test with export BITBUCKET_DOCKER_HOST_INTERNAL=host.docker.internal (as a IP address 192.168.65.2 check by ping host.docker.internal from container)
    environment:
      - REDIS_URL=redis://:PLEASE_CHANGE_ME@redis:6379
      - POSTGRESQL_URL=postgresql://postgres:root@database_test:5432/notino_test
      - JWT_SECRET=ewfjweiofjowimfkewnmfoin
      - AWS_S3_BUCKET=sample-bucket
      - AWS_S3_REGION=eu-central-1
      - AWS_S3_ACCESS_KEY_ID=test
      - AWS_S3_SECRET_KEY=test
      - AWS_KEYPAIR_ID=testa
      - NODE_ENV=production
      - AWS_S3_PUBLIC_URL=http://sample-bucket.s3.eu-central-1.localhost:4566
      - AWS_S3_ENDPOINT=http://s3.eu-central-1.localhost:4566
      - SERVICES_SUGGESTION_EMAILS=test@goodrequest.com
      - USE_CLOUD_WATCH=false
      - BULLMQ_INIT_JOBS=true
      - BULLMQ_DASHBOARD_USERNAME=admin
      - BULLMQ_DASHBOARD_PASSWORD=Lopaty123.
      - BULLMQ_DASHBOARD_SESSION_SECRET=dnaidbapdndioabd
      - WHITELIST_EMAILS=@goodrequest.com
      # in bitbucket pipeline do not work docker.host.internal instead of it has to be used $BITBUCKET_DOCKER_HOST_INTERNAL variable
      - SMTP_HOST=$BITBUCKET_DOCKER_HOST_INTERNAL
      # mail server is running with cypress test define in cypress plugins
      - SMTP_PORT=7777
      - SMTP_FROM_ADDRESS=e2e@goodrequest.com
      - DOMAIN=http://localhost:80
      - BLOOMREACH_CRM={"DEV":{"projectID":"fe26335c-0a04-11eb-8896-b6e81312755b","apiKeyID":"123","apiKeySecret":"E2E"}}
    depends_on:
      - "backend_0"
      - "backend_1"
