// eslint-disable-next-line import/prefer-default-export
export enum EMPLOYEES {
	EMPLOYEES_LOAD_START = 'EMPLOYEES_LOAD_START',
	EMPLOYEES_LOAD_DONE = 'EMPLOYEES_LOAD_DONE',
	EMPLOYEES_LOAD_FAIL = 'EMPLOYEES_LOAD_FAIL',
	EMPLOYEES_REORDER = 'EMPLOYEES_REORDER'
}

export enum EMPLOYEE {
	EMPLOYEE_LOAD_START = 'EMPLOYEE_LOAD_START',
	EMPLOYEE_LOAD_DONE = 'EMPLOYEE_LOAD_DONE',
	EMPLOYEE_LOAD_FAIL = 'EMPLOYEE_LOAD_FAIL'
}
