// eslint-disable-next-line import/prefer-default-export
export enum NOTINO_DASHBOARD {
	NOTINO_DASHBOARD_LOAD_START = 'NOTINO_DASHBOARD_LOAD_START',
	NOTINO_DASHBOARD_LOAD_DONE = 'NOTINO_DASHBOARD_LOAD_DONE',
	NOTINO_DASHBOARD_LOAD_FAIL = 'NOTINO_DASHBOARD_LOAD_FAIL'
}

export enum SALONS_ANNUAL_STATS {
	SALONS_ANNUAL_STATS_LOAD_START = 'SALONS_ANNUAL_STATS_LOAD_START',
	SALONS_ANNUAL_STATS_LOAD_DONE = 'SALONS_ANNUAL_STATS_LOAD_DONE',
	SALONS_ANNUAL_STATS_LOAD_FAIL = 'SALONS_ANNUAL_STATS_LOAD_FAIL'
}

export enum SALONS_MONTH_STATS {
	SALONS_MONTH_STATS_LOAD_START = 'SALONS_MONTH_STATS_LOAD_START',
	SALONS_MONTH_STATS_LOAD_DONE = 'SALONS_MONTH_STATS_LOAD_DONE',
	SALONS_MONTH_STATS_LOAD_FAIL = 'SALONS_MONTH_STATS_LOAD_FAIL'
}
