// eslint-disable-next-line import/prefer-default-export
export enum NOTINO_DASHBOARD {
	NOTINO_DASHBOARD_LOAD_START = 'NOTINO_DASHBOARD_LOAD_START',
	NOTINO_DASHBOARD_LOAD_DONE = 'NOTINO_DASHBOARD_LOAD_DONE',
	NOTINO_DASHBOARD_LOAD_FAIL = 'NOTINO_DASHBOARD_LOAD_FAIL'
}

export enum PARTNER_DASHBOARD {
	PARTNER_DASHBOARD_LOAD_START = 'PARTNER_DASHBOARD_LOAD_START',
	PARTNER_DASHBOARD_LOAD_DONE = 'PARTNER_DASHBOARD_LOAD_DONE',
	PARTNER_DASHBOARD_LOAD_FAIL = 'PARTNER_DASHBOARD_LOAD_FAIL'
}
