// eslint-disable-next-line import/prefer-default-export
export enum SMS_STATS {
	SMS_STATS_LOAD_START = 'SMS_STATS_LOAD_START',
	SMS_STATS_LOAD_DONE = 'SMS_STATS_LOAD_DONE',
	SMS_STATS_LOAD_FAIL = 'SMS_STATS_LOAD_FAIL'
}

export enum SMS_TIME_STATS {
	SMS_TIME_STATS_LOAD_START = 'SMS_TIME_STATS_LOAD_START',
	SMS_TIME_STATS_LOAD_DONE = 'SMS_TIME_STATS_LOAD_DONE',
	SMS_TIME_STATS_LOAD_FAIL = 'SMS_TIME_STATS_LOAD_FAIL'
}

export enum SMS_HISTORY {
	SMS_HISTORY_LOAD_START = 'SMS_HISTORY_LOAD_START',
	SMS_HISTORY_LOAD_DONE = 'SMS_HISTORY_LOAD_DONE',
	SMS_HISTORY_LOAD_FAIL = 'SMS_HISTORY_LOAD_FAIL'
}
