/* eslint-disable import/prefer-default-export */
export enum ENUMERATIONS {
	ENUMERATIONS_LOAD_START = 'ENUMERATIONS_LOAD_START',
	ENUMERATIONS_LOAD_DONE = 'ENUMERATIONS_LOAD_DONE',
	ENUMERATIONS_LOAD_FAIL = 'ENUMERATIONS_LOAD_FAIL',
	ENUMERATIONS_LOAD_REORDER = 'ENUMERATIONS_LOAD_REORDER'
}
