enum SELECTED_SALON {
	SELECTED_SALON_LOAD_START = 'SELECTED_SALON_LOAD_START',
	SELECTED_SALON_LOAD_DONE = 'SELECTED_SALON_LOAD_DONE',
	SELECTED_SALON_LOAD_FAIL = 'SELECTED_SALON_LOAD_FAIL'
}

export default SELECTED_SALON
