// eslint-disable-next-line import/prefer-default-export
export enum SERVICES {
	SERVICES_LOAD_START = 'SERVICES_LOAD_START',
	SERVICES_LOAD_DONE = 'SERVICES_LOAD_DONE',
	SERVICES_LOAD_FAIL = 'SERVICES_LOAD_FAIL'
}

export enum SERVICE {
	SERVICE_LOAD_START = 'SERVICE_LOAD_START',
	SERVICE_LOAD_DONE = 'SERVICE_LOAD_DONE',
	SERVICE_LOAD_FAIL = 'SERVICE_LOAD_FAIL'
}

export enum SERVICE_ROOT_CATEGORY {
	SERVICE_ROOT_CATEGORY_LOAD_START = 'SERVICE_ROOT_CATEGORY_LOAD_START',
	SERVICE_ROOT_CATEGORY_LOAD_DONE = 'SERVICE_ROOT_CATEGORY_LOAD_DONE',
	SERVICE_ROOT_CATEGORY_LOAD_FAIL = 'SERVICE_ROOT_CATEGORY_LOAD_FAIL'
}
