// eslint-disable-next-line import/prefer-default-export
export enum SALONS {
	SALONS_LOAD_START = 'SALONS_LOAD_START',
	SALONS_LOAD_DONE = 'SALONS_LOAD_DONE',
	SALONS_LOAD_FAIL = 'SALONS_LOAD_FAIL'
}

export enum SALON {
	SALON_LOAD_START = 'SALON_LOAD_START',
	SALON_LOAD_DONE = 'SALON_LOAD_DONE',
	SALON_LOAD_FAIL = 'SALON_LOAD_FAIL'
}

export enum SUGGESTED_SALONS {
	SUGGESTED_SALONS_LOAD_START = 'SUGGESTED_SALONS_LOAD_START',
	SUGGESTED_SALONS_LOAD_DONE = 'SUGGESTED_SALONS_LOAD_DONE',
	SUGGESTED_SALONS_LOAD_FAIL = 'SUGGESTED_SALONS_LOAD_FAIL'
}
