// eslint-disable-next-line import/prefer-default-export
export enum CATEGORIES {
	CATEGORIES_LOAD_START = 'CATEGORIES_LOAD_START',
	CATEGORIES_LOAD_DONE = 'CATEGORIES_LOAD_DONE',
	CATEGORIES_LOAD_FAIL = 'CATEGORIES_LOAD_FAIL'
}

export enum CATEGORY {
	CATEGORY_LOAD_START = 'CATEGORY_LOAD_START',
	CATEGORY_LOAD_DONE = 'CATEGORY_LOAD_DONE',
	CATEGORY_LOAD_FAIL = 'CATEGORY_LOAD_FAIL'
}
